version: '2.1'

services:
  parcel-react-ssr:
    image: parcel-react-ssr
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 1234:1234
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 dist/server